# python scraper_request.py --manufacturer "Mazda" --model "CX-5"

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Tuple

import requests
from loguru import logger

CUR_DIR = Path(__file__).parent
OUTPUT_DIR = CUR_DIR / "output"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RESULT_FILENAME = OUTPUT_DIR / "result.jsonl"

USER_DATA_DIR = CUR_DIR / "user_data_dir"
EXT_DIR = CUR_DIR / "uBlock0.chromium"

API_ENDPOINT = "https://weblabapi.com/ads/list"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.160 Safari/537.36"
HTTP_TIMEOUT = 15.0
BRANDS = [
    {
        "name": "AC",
        "seo": "ac",
        "description": None,
        "logo": None,
        "id": 2,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "ACM",
        "seo": "acm",
        "description": None,
        "logo": None,
        "id": 3,
        "createdAt": None,
        "updatedAt": "2023-03-17T16:54:37.000Z",
        "stared": False,
    },
    {
        "name": "Abarth",
        "seo": "abarth",
        "description": "null",
        "logo": "brands/554f361d-12a2-4ee5-98ec-ceb3fd9bd24e.png",
        "id": 1,
        "createdAt": None,
        "updatedAt": "2019-12-18T13:24:07.000Z",
        "stared": False,
    },
    {
        "name": "Acura",
        "seo": "acura",
        "description": None,
        "logo": None,
        "id": 4,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Aixam",
        "seo": "aixam",
        "description": None,
        "logo": None,
        "id": 5,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Alfa Romeo",
        "seo": "alfa-romeo",
        "description": "null",
        "logo": "brands/5a275efe-0877-42a5-b20f-9124f3a20970.png",
        "id": 6,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:02:52.000Z",
        "stared": True,
    },
    {
        "name": "Alpina",
        "seo": "alpina",
        "description": None,
        "logo": None,
        "id": 7,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Alpine",
        "seo": "alpine",
        "description": None,
        "logo": None,
        "id": 8,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Amphicar",
        "seo": "amphicar",
        "description": None,
        "logo": None,
        "id": 9,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Ariel Motor",
        "seo": "ariel-motor",
        "description": None,
        "logo": None,
        "id": 10,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Aro",
        "seo": "aro",
        "description": None,
        "logo": None,
        "id": 13,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Artega",
        "seo": "artega",
        "description": None,
        "logo": None,
        "id": 11,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Asia Motors",
        "seo": "asia-motors",
        "description": None,
        "logo": None,
        "id": 14,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Aspid",
        "seo": "aspid",
        "description": None,
        "logo": None,
        "id": 12,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Aston Martin",
        "seo": "aston-martin",
        "description": None,
        "logo": None,
        "id": 15,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Audi",
        "seo": "audi",
        "description": None,
        "logo": "brands/9f8e1938-f898-4dc5-83dc-71ffe4f2c838.png",
        "id": 16,
        "createdAt": None,
        "updatedAt": "2023-03-10T13:16:09.000Z",
        "stared": True,
    },
    {
        "name": "Austin",
        "seo": "austin",
        "description": None,
        "logo": None,
        "id": 17,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Autobianchi",
        "seo": "autobianchi",
        "description": None,
        "logo": None,
        "id": 18,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Auverland",
        "seo": "auverland",
        "description": None,
        "logo": None,
        "id": 19,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "BMW",
        "seo": "bmw",
        "description": None,
        "logo": "brands/2e7d72e1-5289-413c-9bf1-aad242f51299.png",
        "id": 24,
        "createdAt": None,
        "updatedAt": "2023-03-16T16:37:33.000Z",
        "stared": True,
    },
    {
        "name": "BYD",
        "seo": "byd",
        "description": None,
        "logo": None,
        "id": 30,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Baic",
        "seo": "baic",
        "description": None,
        "logo": None,
        "id": 20,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Bedford",
        "seo": "bedford",
        "description": None,
        "logo": None,
        "id": 21,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Bellier",
        "seo": "bellier",
        "description": None,
        "logo": None,
        "id": 22,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Bentley",
        "seo": "bentley",
        "description": None,
        "logo": None,
        "id": 23,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Bolloré",
        "seo": "bollore",
        "description": None,
        "logo": None,
        "id": 25,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Borgward",
        "seo": "borgward",
        "description": None,
        "logo": None,
        "id": 26,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Brilliance",
        "seo": "brilliance",
        "description": None,
        "logo": None,
        "id": 27,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Bugatti",
        "seo": "bugatti",
        "description": None,
        "logo": None,
        "id": 28,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Buick",
        "seo": "buick",
        "description": None,
        "logo": None,
        "id": 29,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "CMC",
        "seo": "cmc",
        "description": None,
        "logo": None,
        "id": 42,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Cadillac",
        "seo": "cadillac",
        "description": None,
        "logo": None,
        "id": 31,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Casalini",
        "seo": "casalini",
        "description": None,
        "logo": None,
        "id": 32,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Caterham",
        "seo": "caterham",
        "description": None,
        "logo": None,
        "id": 33,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Changhe",
        "seo": "changhe",
        "description": None,
        "logo": None,
        "id": 34,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Chatenet",
        "seo": "chatenet",
        "description": None,
        "logo": None,
        "id": 35,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Chery",
        "seo": "chery",
        "description": None,
        "logo": None,
        "id": 36,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Chevrolet",
        "seo": "chevrolet",
        "description": "null",
        "logo": "brands/00e45186-4e47-4d03-b31c-e6c1fbbef119.png",
        "id": 37,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:05:14.000Z",
        "stared": False,
    },
    {
        "name": "Chrysler",
        "seo": "chrysler",
        "description": "null",
        "logo": "brands/43ca6074-9261-4ed1-98ab-245fd77171ee.png",
        "id": 38,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:04:41.000Z",
        "stared": False,
    },
    {
        "name": "Citroen",
        "seo": "citroen",
        "description": "null",
        "logo": "brands/fd6e6a19-2d8c-4361-8c7b-97de444fc78f.png",
        "id": 39,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:03:33.000Z",
        "stared": True,
    },
    {
        "name": "CityEL",
        "seo": "cityel",
        "description": None,
        "logo": None,
        "id": 40,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Corvette",
        "seo": "corvette",
        "description": None,
        "logo": None,
        "id": 41,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Courb",
        "seo": "courb",
        "description": None,
        "logo": None,
        "id": 43,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Cupra",
        "seo": "cupra",
        "description": None,
        "logo": None,
        "id": 70990,
        "createdAt": "2023-10-23T16:54:11.000Z",
        "updatedAt": "2023-10-23T16:54:11.000Z",
        "stared": False,
    },
    {
        "name": "DR Motor",
        "seo": "dr-motor",
        "description": None,
        "logo": None,
        "id": 52,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "DS Automobiles",
        "seo": "ds-automobiles",
        "description": None,
        "logo": None,
        "id": 53,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Dacia",
        "seo": "dacia",
        "description": "null",
        "logo": "brands/54668f99-b55d-4c68-b86b-9f3132b8ec26.png",
        "id": 44,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:05:07.000Z",
        "stared": False,
    },
    {
        "name": "Daewoo",
        "seo": "daewoo",
        "description": "null",
        "logo": "brands/d705f7bd-8a94-47dd-86db-9bc873544190.png",
        "id": 45,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:05:20.000Z",
        "stared": False,
    },
    {
        "name": "Daihatsu",
        "seo": "daihatsu",
        "description": "null",
        "logo": "brands/b1644f53-c007-43cc-87a0-3c1150819a75.png",
        "id": 49,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:05:33.000Z",
        "stared": False,
    },
    {
        "name": "Daimler",
        "seo": "daimler",
        "description": None,
        "logo": None,
        "id": 46,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "De Tomaso",
        "seo": "de-tomaso",
        "description": None,
        "logo": None,
        "id": 48,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "De la Chapelle",
        "seo": "de-la-chapelle",
        "description": None,
        "logo": None,
        "id": 47,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Dodge",
        "seo": "dodge",
        "description": None,
        "logo": None,
        "id": 50,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Donkervoort",
        "seo": "donkervoort",
        "description": None,
        "logo": None,
        "id": 51,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Dutton",
        "seo": "dutton",
        "description": None,
        "logo": None,
        "id": 54,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Ferrari",
        "seo": "ferrari",
        "description": None,
        "logo": None,
        "id": 56,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Fiat",
        "seo": "fiat",
        "description": "null",
        "logo": "brands/1fd046d6-1417-4bbc-b4f4-4d3025d90d40.png",
        "id": 57,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:06:25.000Z",
        "stared": True,
    },
    {
        "name": "Fisker",
        "seo": "fisker",
        "description": None,
        "logo": None,
        "id": 58,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Ford",
        "seo": "ford",
        "description": "null",
        "logo": "brands/b826b653-2364-4083-a154-5eeed35a9403.png",
        "id": 59,
        "createdAt": None,
        "updatedAt": "2019-12-18T15:06:38.000Z",
        "stared": True,
    },
    {
        "name": "GAC Gonow",
        "seo": "gac-gonow",
        "description": None,
        "logo": None,
        "id": 60,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "GAZ",
        "seo": "gaz",
        "description": None,
        "logo": None,
        "id": 62,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "GEM",
        "seo": "gem",
        "description": None,
        "logo": None,
        "id": 64,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "GEMBALLA",
        "seo": "gemballa",
        "description": None,
        "logo": None,
        "id": 65,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "GMC",
        "seo": "gmc",
        "description": None,
        "logo": None,
        "id": 67,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Galloper",
        "seo": "galloper",
        "description": None,
        "logo": None,
        "id": 61,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Geely",
        "seo": "geely",
        "description": None,
        "logo": None,
        "id": 63,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Genesis",
        "seo": "genesis",
        "description": None,
        "logo": None,
        "id": 66,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Great Wall",
        "seo": "great-wall",
        "description": None,
        "logo": None,
        "id": 68,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Haima",
        "seo": "haima",
        "description": None,
        "logo": None,
        "id": 69,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Honda",
        "seo": "honda",
        "description": "null",
        "logo": "brands/4300c7f7-b468-44fc-8353-c820ac19cc3e.png",
        "id": 70,
        "createdAt": None,
        "updatedAt": "2020-06-26T11:22:05.000Z",
        "stared": False,
    },
    {
        "name": "Hummer",
        "seo": "hummer",
        "description": None,
        "logo": None,
        "id": 71,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Hurtan",
        "seo": "hurtan",
        "description": None,
        "logo": None,
        "id": 72,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Hyundai",
        "seo": "hyundai",
        "description": "null",
        "logo": "brands/1bc791a2-bf42-4844-bf13-f21424f686e4.png",
        "id": 73,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:59:10.000Z",
        "stared": False,
    },
    {
        "name": "IZH",
        "seo": "izh",
        "description": None,
        "logo": None,
        "id": 79,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Infiniti",
        "seo": "infiniti",
        "description": None,
        "logo": None,
        "id": 74,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Innocenti",
        "seo": "innocenti",
        "description": None,
        "logo": None,
        "id": 75,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Iso Rivolta",
        "seo": "iso-rivolta",
        "description": None,
        "logo": None,
        "id": 76,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Isuzu",
        "seo": "isuzu",
        "description": "null",
        "logo": "brands/2bc17cf3-53e8-4f6b-a8c2-2950aae615d9.png",
        "id": 77,
        "createdAt": None,
        "updatedAt": "2019-12-18T13:57:44.000Z",
        "stared": False,
    },
    {
        "name": "Iveco",
        "seo": "iveco",
        "description": None,
        "logo": None,
        "id": 78,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Jaguar",
        "seo": "jaguar",
        "description": "null",
        "logo": "brands/32e632c1-6e4f-49ea-8372-ca631307f3bf.png",
        "id": 80,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:03:13.000Z",
        "stared": False,
    },
    {
        "name": "Jeep",
        "seo": "jeep",
        "description": "null",
        "logo": "brands/a383fe44-00d1-4f53-a7ff-20792bba86b7.png",
        "id": 81,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:06:55.000Z",
        "stared": False,
    },
    {
        "name": "KTM",
        "seo": "ktm",
        "description": "null",
        "logo": "brands/028de01b-42c6-4d08-930b-cfd73b1eb1a8.png",
        "id": 85,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:13:36.000Z",
        "stared": False,
    },
    {
        "name": "Katay Gonow",
        "seo": "katay-gonow",
        "description": None,
        "logo": None,
        "id": 82,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Kia",
        "seo": "kia",
        "description": "null",
        "logo": "brands/e32f12fc-9fec-49ff-aab7-3de76f2e8b47.png",
        "id": 83,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:06:19.000Z",
        "stared": False,
    },
    {
        "name": "Koenigsegg",
        "seo": "koenigsegg",
        "description": None,
        "logo": None,
        "id": 84,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Lada",
        "seo": "lada",
        "description": "null",
        "logo": "brands/b811edac-825c-4bf9-a67a-218fa3d0ab4a.png",
        "id": 86,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:05:45.000Z",
        "stared": False,
    },
    {
        "name": "Lamborghini",
        "seo": "lamborghini",
        "description": None,
        "logo": None,
        "id": 87,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Lancia",
        "seo": "lancia",
        "description": "null",
        "logo": "brands/3c2d83a5-e7d7-4559-922b-d28510c951c7.png",
        "id": 88,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:02:59.000Z",
        "stared": False,
    },
    {
        "name": "Land Rover",
        "seo": "land-rover",
        "description": "null",
        "logo": "brands/6f3fe3d8-f452-4428-a7cd-90f58052a8fd.png",
        "id": 89,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:07:13.000Z",
        "stared": False,
    },
    {
        "name": "Lexus",
        "seo": "lexus",
        "description": "null",
        "logo": "brands/484cdfe3-7af7-4b21-b0da-c85f9da77e51.png",
        "id": 90,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:06:38.000Z",
        "stared": False,
    },
    {
        "name": "Lifan",
        "seo": "lifan",
        "description": None,
        "logo": None,
        "id": 91,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Ligier",
        "seo": "ligier",
        "description": None,
        "logo": None,
        "id": 92,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Lincoln",
        "seo": "lincoln",
        "description": None,
        "logo": None,
        "id": 93,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Lotus",
        "seo": "lotus",
        "description": None,
        "logo": None,
        "id": 94,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "MG",
        "seo": "mg",
        "description": None,
        "logo": None,
        "id": 105,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "MPM Motors",
        "seo": "mpm-motors",
        "description": None,
        "logo": None,
        "id": 110,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Mahindra",
        "seo": "mahindra",
        "description": None,
        "logo": None,
        "id": 95,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Martin Motors",
        "seo": "martin-motors",
        "description": None,
        "logo": None,
        "id": 96,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Maserati",
        "seo": "maserati",
        "description": None,
        "logo": None,
        "id": 97,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Maybach",
        "seo": "maybach",
        "description": None,
        "logo": None,
        "id": 98,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Mazda",
        "seo": "mazda",
        "description": "null",
        "logo": "brands/4913a72d-18b7-473a-bbb5-45b9c914e89e.png",
        "id": 99,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:14:06.000Z",
        "stared": False,
    },
    {
        "name": "McLaren",
        "seo": "mclaren",
        "description": None,
        "logo": None,
        "id": 100,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Mercedes Benz",
        "seo": "mercedes-benz",
        "description": "null",
        "logo": "brands/70094de9-1f3b-4620-b252-8e0bdcb384d1.png",
        "id": 101,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:45:15.000Z",
        "stared": True,
    },
    {
        "name": "Mercury",
        "seo": "mercury",
        "description": None,
        "logo": None,
        "id": 102,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Microcar",
        "seo": "microcar",
        "description": None,
        "logo": None,
        "id": 104,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Mini",
        "seo": "mini",
        "description": "null",
        "logo": "brands/ef8c2039-8322-4818-96ec-6a8e1b3d0b1c.png",
        "id": 103,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:57:16.000Z",
        "stared": False,
    },
    {
        "name": "Mitsubishi",
        "seo": "mitsubishi",
        "description": "null",
        "logo": "brands/6d744c4b-549e-4b8d-9d5d-200a644742f7.png",
        "id": 106,
        "createdAt": None,
        "updatedAt": "2019-12-18T19:54:34.000Z",
        "stared": False,
    },
    {
        "name": "Mitsuoka",
        "seo": "mitsuoka",
        "description": None,
        "logo": None,
        "id": 107,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Morgan",
        "seo": "morgan",
        "description": None,
        "logo": None,
        "id": 108,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Moskvich",
        "seo": "moskvich",
        "description": None,
        "logo": None,
        "id": 109,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Nissan",
        "seo": "nissan",
        "description": "null",
        "logo": "brands/bf2d36e6-37b2-41e8-aeb1-3f12b69a03c0.png",
        "id": 111,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:02:32.000Z",
        "stared": True,
    },
    {
        "name": "Oldsmobile",
        "seo": "oldsmobile",
        "description": None,
        "logo": None,
        "id": 112,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Opel",
        "seo": "opel",
        "description": "null",
        "logo": "brands/3ad4d067-9b99-4664-8251-7c95633a7901.png",
        "id": 113,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:02:01.000Z",
        "stared": True,
    },
    {
        "name": "Ostalo",
        "seo": "ostalo",
        "description": None,
        "logo": None,
        "id": 3566,
        "createdAt": "2019-08-02T08:29:55.000Z",
        "updatedAt": "2019-08-02T08:29:55.000Z",
        "stared": False,
    },
    {
        "name": "PGO",
        "seo": "pgo",
        "description": None,
        "logo": None,
        "id": 117,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Pagani",
        "seo": "pagani",
        "description": None,
        "logo": None,
        "id": 114,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Panther Westwinds",
        "seo": "panther-westwinds",
        "description": None,
        "logo": None,
        "id": 115,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Peugeot",
        "seo": "peugeot",
        "description": "null",
        "logo": "brands/18d238e4-1329-4e37-8277-b4acc049f39a.png",
        "id": 116,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:09:03.000Z",
        "stared": True,
    },
    {
        "name": "Piaggio",
        "seo": "piaggio",
        "description": "null",
        "logo": "brands/f4e2e40b-e911-4d18-a969-6608097d209f.png",
        "id": 118,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:54:45.000Z",
        "stared": False,
    },
    {
        "name": "Plymouth",
        "seo": "plymouth",
        "description": None,
        "logo": None,
        "id": 119,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Polonez",
        "seo": "polonez",
        "description": None,
        "logo": None,
        "id": 120,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Polski Fiat",
        "seo": "polski-fiat",
        "description": None,
        "logo": None,
        "id": 121,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Pontiac",
        "seo": "pontiac",
        "description": None,
        "logo": None,
        "id": 122,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Porsche",
        "seo": "porsche",
        "description": "null",
        "logo": "brands/bc8da860-f5a1-4c52-bcf9-a37ab3ce1c28.png",
        "id": 123,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:00:16.000Z",
        "stared": False,
    },
    {
        "name": "Proton",
        "seo": "proton",
        "description": None,
        "logo": None,
        "id": 124,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Puch",
        "seo": "puch",
        "description": None,
        "logo": None,
        "id": 125,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Qoros",
        "seo": "qoros",
        "description": None,
        "logo": None,
        "id": 126,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Qvale",
        "seo": "qvale",
        "description": None,
        "logo": None,
        "id": 127,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "RAM",
        "seo": "ram",
        "description": None,
        "logo": None,
        "id": 128,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Rayton Fissore",
        "seo": "rayton-fissore",
        "description": None,
        "logo": None,
        "id": 129,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Reliant",
        "seo": "reliant",
        "description": None,
        "logo": None,
        "id": 130,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Renault",
        "seo": "renault",
        "description": "null",
        "logo": "brands/762a7cbe-8798-4670-9964-627b36113d6d.png",
        "id": 131,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:44:44.000Z",
        "stared": True,
    },
    {
        "name": "Rolls Royce",
        "seo": "rolls-royce",
        "description": None,
        "logo": None,
        "id": 132,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Rover",
        "seo": "rover",
        "description": "null",
        "logo": "brands/3d8b5c6f-243f-4198-8c85-ca4f110af960.png",
        "id": 133,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:57:54.000Z",
        "stared": False,
    },
    {
        "name": "Ruf",
        "seo": "ruf",
        "description": None,
        "logo": None,
        "id": 134,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Saab",
        "seo": "saab",
        "description": None,
        "logo": None,
        "id": 135,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Santana",
        "seo": "santana",
        "description": None,
        "logo": None,
        "id": 137,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Saturn",
        "seo": "saturn",
        "description": None,
        "logo": None,
        "id": 136,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Seat",
        "seo": "seat",
        "description": None,
        "logo": "brands/40f1b6bc-1ed2-44fd-98fc-60213f2da3ab.png",
        "id": 138,
        "createdAt": None,
        "updatedAt": "2023-03-10T13:17:26.000Z",
        "stared": True,
    },
    {
        "name": "Shuanghuan",
        "seo": "shuanghuan",
        "description": None,
        "logo": None,
        "id": 139,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Simca",
        "seo": "simca",
        "description": None,
        "logo": None,
        "id": 140,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Smart",
        "seo": "smart",
        "description": "null",
        "logo": "brands/d2baaced-014f-491e-b20e-adca41d3eff0.png",
        "id": 141,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:59:56.000Z",
        "stared": False,
    },
    {
        "name": "Spyker",
        "seo": "spyker",
        "description": None,
        "logo": None,
        "id": 142,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "SsangYong",
        "seo": "ssangyong",
        "description": "null",
        "logo": "brands/2093bea0-082c-43d9-acf5-b40644b15090.png",
        "id": 143,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:59:41.000Z",
        "stared": False,
    },
    {
        "name": "Subaru",
        "seo": "subaru",
        "description": "null",
        "logo": "brands/81ceb3c7-ace5-484d-afca-c82769a4dee3.png",
        "id": 144,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:01:37.000Z",
        "stared": False,
    },
    {
        "name": "Suzuki",
        "seo": "suzuki",
        "description": "null",
        "logo": "brands/66f3e514-d6f6-471b-9510-530faf46fd52.png",
        "id": 145,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:58:14.000Z",
        "stared": False,
    },
    {
        "name": "TVR",
        "seo": "tvr",
        "description": None,
        "logo": None,
        "id": 158,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "TagAZ",
        "seo": "tagaz",
        "description": None,
        "logo": None,
        "id": 147,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Talbot",
        "seo": "talbot",
        "description": None,
        "logo": None,
        "id": 148,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Tasso",
        "seo": "tasso",
        "description": None,
        "logo": None,
        "id": 149,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Tata",
        "seo": "tata",
        "description": None,
        "logo": None,
        "id": 150,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Tavria",
        "seo": "tavria",
        "description": None,
        "logo": None,
        "id": 153,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Tazzari Ev",
        "seo": "tazzari-ev",
        "description": None,
        "logo": None,
        "id": 151,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Tesla",
        "seo": "tesla",
        "description": None,
        "logo": None,
        "id": 152,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Town Life",
        "seo": "town-life",
        "description": None,
        "logo": None,
        "id": 154,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Toyota",
        "seo": "toyota",
        "description": "null",
        "logo": "brands/84d06b04-9402-443f-bc79-e7e40fcc1bdd.png",
        "id": 155,
        "createdAt": None,
        "updatedAt": "2019-12-23T18:25:49.000Z",
        "stared": True,
    },
    {
        "name": "Trabant",
        "seo": "trabant",
        "description": None,
        "logo": None,
        "id": 156,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Triumph",
        "seo": "triumph",
        "description": None,
        "logo": None,
        "id": 157,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "UAZ",
        "seo": "uaz",
        "description": None,
        "logo": None,
        "id": 159,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Volkswagen",
        "seo": "volkswagen",
        "description": None,
        "logo": "brands/24d3c8bc-fa6c-473f-9698-d5a7352b4a54.png",
        "id": 160,
        "createdAt": None,
        "updatedAt": "2023-03-10T13:19:40.000Z",
        "stared": True,
    },
    {
        "name": "Volvo",
        "seo": "volvo",
        "description": "null",
        "logo": "brands/a8fe7566-f814-4b73-9b6e-bff75f302305.png",
        "id": 161,
        "createdAt": None,
        "updatedAt": "2020-01-15T16:57:36.000Z",
        "stared": True,
    },
    {
        "name": "Vortex",
        "seo": "vortex",
        "description": None,
        "logo": None,
        "id": 162,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Wartburg",
        "seo": "wartburg",
        "description": None,
        "logo": None,
        "id": 163,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Westfield",
        "seo": "westfield",
        "description": None,
        "logo": None,
        "id": 164,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Wiesmann",
        "seo": "wiesmann",
        "description": None,
        "logo": None,
        "id": 165,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "XEV",
        "seo": "xev",
        "description": None,
        "logo": None,
        "id": 70992,
        "createdAt": "2023-11-04T13:44:23.000Z",
        "updatedAt": "2023-11-04T13:44:23.000Z",
        "stared": False,
    },
    {
        "name": "ZAZ",
        "seo": "zaz",
        "description": None,
        "logo": None,
        "id": 167,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Zastava",
        "seo": "zastava",
        "description": "null",
        "logo": None,
        "id": 166,
        "createdAt": None,
        "updatedAt": "2020-02-20T17:46:00.000Z",
        "stared": False,
    },
    {
        "name": "e.GO",
        "seo": "e-go",
        "description": None,
        "logo": None,
        "id": 55,
        "createdAt": None,
        "updatedAt": None,
        "stared": False,
    },
    {
        "name": "Škoda",
        "seo": "skoda",
        "description": "null",
        "logo": "brands/601d1576-5ef3-490d-9a90-bb4717da249c.png",
        "id": 146,
        "createdAt": None,
        "updatedAt": "2020-01-15T17:02:15.000Z",
        "stared": True,
    },
]

CITY_LIST = [
    {"id": 1, "label": "Bar", "seo": "bar", "value": 1},
    {"id": 2, "label": "Budva", "seo": "budva", "value": 2},
    {"id": 3, "label": "Herceg Novi", "seo": "herceg-novi", "value": 3},
    {"id": 4, "label": "Kotor", "seo": "kotor", "value": 4},
    {"id": 5, "label": "Tivat", "seo": "tivat", "value": 5},
    {"id": 6, "label": "Ulcinj", "seo": "ulcinj", "value": 6},
    {"id": 7, "label": "Cetinje", "seo": "cetinje", "value": 7},
    {"id": 8, "label": "Danilovgrad", "seo": "danilovgrad", "value": 8},
    {"id": 9, "label": "Nik\u0161i\u0107", "seo": "niksic", "value": 9},
    {"id": 10, "label": "Podgorica", "seo": "podgorica", "value": 10},
    {"id": 11, "label": "Andrijevica", "seo": "andrijevica", "value": 11},
    {"id": 12, "label": "Berane", "seo": "berane", "value": 12},
    {"id": 13, "label": "Bijelo Polje", "seo": "bijelo-polje", "value": 13},
    {"id": 14, "label": "Gusinje", "seo": "gusinje", "value": 14},
    {"id": 15, "label": "Kola\u0161in", "seo": "kolasin", "value": 15},
    {"id": 16, "label": "Mojkovac", "seo": "mojkovac", "value": 16},
    {"id": 17, "label": "Petnjica", "seo": "petnjica", "value": 17},
    {"id": 18, "label": "Plav", "seo": "plav", "value": 18},
    {"id": 19, "label": "Pljevlja", "seo": "pljevlja", "value": 19},
    {"id": 20, "label": "Plu\u017eine", "seo": "pluzine", "value": 20},
    {"id": 21, "label": "Ro\u017eaje", "seo": "rozaje", "value": 21},
    {"id": 22, "label": "\u0160avnik", "seo": "savnik", "value": 22},
    {"id": 23, "label": "\u017dabljak", "seo": "zabljak", "value": 23},
]


def get_brand_id_seo(brand_name: str) -> Tuple[int, str]:
    for brand in BRANDS:
        if brand["name"] == brand_name:
            return brand["id"], brand["seo"]
    raise ValueError(f"brand not found: `{brand_name}`")


def get_product_id(brand_id: int, model_name: str) -> int:
    response = requests.post(
        "https://weblabapi.com/product/listByBrandAndCategory",
        json={
            "brand": brand_id,
            "category": 2,
            "locale": "ME",
        },
        headers={"User-Agent": USER_AGENT},
        timeout=HTTP_TIMEOUT,
    )

    # Print the response
    if response.status_code == 200:
        resp = response.json()
        for product in resp["products"]:
            if product["model"] == model_name:
                return product["id"]
    else:
        print(f"Request failed with status code {response.status_code}")
        print("Error response:", response.text)

    raise ValueError(f"product not found: {brand_id} / {model_name}")


def get_city_id_seo(city_label: str) -> Tuple[int, str]:
    for city in CITY_LIST:
        if city["label"] == city_label:
            return (city["id"], city["seo"])
    raise ValueError(f"city not found: {city_label}")


def build_filter_payload(
    manufacturer: str = "",
    model: str = "",
    body: str = "",
    fuel: str = "",
    mileage_min: str = "",
    mileage_max: str = "",
    engine_displ_min: str = "",
    engine_displ_max: str = "",
    year_min: str = "",
    year_max: str = "",
    price_min: str = "",
    price_max: str = "",
    transmission: str = "",
    city: str = "",
    page_number: int = 1,
) -> Dict[str, Any]:
    filter_payload = {
        "type": "all",
        "page": str(page_number),
        "limit": 36,
        "category": 2,
        "sortBy": "dateDesc",
        "status": "Published",
        "locale": "ME",
    }
    filter_payload["specifications"] = []

    if manufacturer != "":
        brand_id, brand_seo = get_brand_id_seo(manufacturer)
        filter_payload["brands"] = [str(brand_id)]
        filter_payload["brandsText"] = [manufacturer]
        filter_payload["brandBc"] = {"seo": brand_seo, "text": manufacturer}

    if model != "":
        product_id = get_product_id(brand_id, model)
        filter_payload["modelBc"] = {"text": model}
        filter_payload["products"] = [str(product_id)]
        filter_payload["productsText"] = [f"{manufacturer} {model}"]

    if body != "":
        filter_payload["specifications"].append(
            {"id": "7", "values": [body]},  # body
        )

    if fuel != "":
        filter_payload["specifications"].append(
            {"id": "9", "value": fuel},  # fuel
        )

    if mileage_min != "" and mileage_max != "":
        filter_payload["specifications"].append(
            {"id": "3", "range": {"from": mileage_min, "to": mileage_max}}  # mileage
        )

    if engine_displ_min != "" and engine_displ_max != "":
        filter_payload["specifications"].append(
            {
                "id": "4",
                "range": {"from": engine_displ_min, "to": engine_displ_max},
            },  # engine displacement
        )

    if year_min != "" and year_max != "":
        filter_payload["specifications"].append(
            {"id": "8", "range": {"from": year_min, "to": year_max}},  # year
        )

    if price_min != "" and price_max != "":
        filter_payload["price"] = [str(price_min), str(price_max)]

    if transmission != "":
        filter_payload["specifications"].append(
            {"id": "12", "value": transmission},  # transmission
        )

    if city != "":
        city_id, city_seo = get_city_id_seo(city)
        filter_payload["citiesText"] = [city]
        filter_payload["cityBc"] = {"seo": city_seo, "text": city}
        filter_payload["cities"] = [str(city_id)]

    return filter_payload


def fetch_products(
    manufacturer: str = "",
    model: str = "",
    body: str = "",
    fuel: str = "",
    mileage_min: str = "",
    mileage_max: str = "",
    engine_displ_min: str = "",
    engine_displ_max: str = "",
    year_min: str = "",
    year_max: str = "",
    price_min: str = "",
    price_max: str = "",
    transmission: str = "",
    city: str = "",
    page_number: int = 1,
) -> Dict[str, Any]:
    payload = build_filter_payload(
        manufacturer,
        model,
        body,
        fuel,
        mileage_min,
        mileage_max,
        engine_displ_min,
        engine_displ_max,
        year_min,
        year_max,
        price_min,
        price_max,
        transmission,
        city,
        page_number,
    )
    response = requests.post(
        API_ENDPOINT,
        json=payload,
        headers={"User-Agent": USER_AGENT},
        timeout=HTTP_TIMEOUT,
    )

    if response.status_code == 200:
        resp = response.json()
        return resp

        paid_count = resp["paidCount"]
        free_count = resp["freeCount"]
        total_count = paid_count + free_count

        print(f"paid: {paid_count}")
        print(f"free: {free_count}")
        print(f"free: {total_count}")

    else:
        print(f"Request failed with status code {response.status_code}")
        print("Error response:", response.text)

    raise ValueError(f"request failed: {payload}")


def get_filters_from_args():
    parser = argparse.ArgumentParser(description="Filter car data based on parameters.")
    parser.add_argument(
        "--manufacturer",
        type=str,
        default="",
        help="Manufacturer of the car",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="",
        help="Model of the car",
    )
    parser.add_argument(
        "--body",
        type=str,
        default="",
        help="Body type of the car",
    )
    parser.add_argument(
        "--fuel",
        type=str,
        default="",
        help="Fuel type of the car",
    )
    parser.add_argument(
        "--mileage_min",
        type=str,
        default="",
        help="Minimum mileage",
    )
    parser.add_argument(
        "--mileage_max",
        type=str,
        default="",
        help="Maximum mileage",
    )
    parser.add_argument(
        "--engine_displ_min",
        type=str,
        default="",
        help="Minimum engine displacement",
    )
    parser.add_argument(
        "--engine_displ_max",
        type=str,
        default="",
        help="Maximum engine displacement",
    )
    parser.add_argument(
        "--year_min",
        type=str,
        default="",
        help="Minimum year of manufacture",
    )
    parser.add_argument(
        "--year_max",
        type=str,
        default="",
        help="Maximum year of manufacture",
    )
    parser.add_argument(
        "--price_min",
        type=str,
        default="",
        help="Minimum price",
    )
    parser.add_argument(
        "--price_max",
        type=str,
        default="",
        help="Maximum price",
    )
    parser.add_argument(
        "--transmission",
        type=str,
        default="",
        help="Transmission type",
    )
    parser.add_argument(
        "--city",
        type=str,
        default="",
        help="City where the car is located",
    )
    args = parser.parse_args()

    # Use the arguments
    print("Manufacturer:", args.manufacturer)
    print("Model:", args.model)
    print("Body:", args.body)
    print("Fuel:", args.fuel)
    print("Mileage Min:", args.mileage_min)
    print("Mileage Max:", args.mileage_max)
    print("Engine Displacement Min:", args.engine_displ_min)
    print("Engine Displacement Max:", args.engine_displ_max)
    print("Year Min:", args.year_min)
    print("Year Max:", args.year_max)
    print("Price Min:", args.price_min)
    print("Price Max:", args.price_max)
    print("Transmission:", args.transmission)
    print("City:", args.city)

    return (
        args.manufacturer,
        args.model,
        args.body,
        args.fuel,
        args.mileage_min,
        args.mileage_max,
        args.engine_displ_min,
        args.engine_displ_max,
        args.year_min,
        args.year_max,
        args.price_min,
        args.price_max,
        args.transmission,
        args.city,
    )


def main():
    filters = get_filters_from_args()
    product_list = []

    total_count = 0
    page_number = 1

    while True:
        logger.info(f"page: {page_number}")

        products = fetch_products(
            manufacturer=filters[0],
            model=filters[1],
            body=filters[2],
            fuel=filters[3],
            mileage_min=filters[4],
            mileage_max=filters[5],
            engine_displ_min=filters[6],
            engine_displ_max=filters[7],
            year_min=filters[8],
            year_max=filters[9],
            price_min=filters[10],
            price_max=filters[11],
            transmission=filters[12],
            city=filters[13],
            page_number=page_number,
        )

        paid_count = products["paidCount"]
        free_count = products["freeCount"]
        total_count = paid_count + free_count

        free_products = products["freeAds"]
        paid_products = products["paidAds"]
        fetched = len(free_products) + len(paid_products)

        product_list.extend(free_products)
        product_list.extend(paid_products)

        logger.info(f"fetched: {fetched} ({len(product_list)}/{total_count})")

        if len(product_list) >= total_count:
            break

        page_number += 1

    with RESULT_FILENAME.open("w", encoding="utf-8") as file:
        for product in product_list:
            product["link"] = f"https://autodiler.me/automobili/{product['seo']}"
            file.write(json.dumps(product, ensure_ascii=False) + "\n")

    logger.info(f"result saved to {RESULT_FILENAME}")


if __name__ == "__main__":
    main()
